#!/usr/bin/env sh

echo "pre-push"
gitbook build --verbose
cd _book
git init
git remote add origin git@github.com:woodlai/note.git
git branch -m gitbook
git add .
git commit -m 'deploy'
git push origin gitbook --force
